[DRAFT] Point-cloud streaming
rapidsai/node pull request #328
Opened 2021-10-26 22:05 UTC by mzegar

1. Created a demo that uses default `PointCloudLayer` to do webrtc streaming 
2. Added demo to the viz app
3. Bringing in the IO module to parse the `.las` file then pass it to the deckgl context

2021-10-29 21:15 UTC, AjayThorve requested changes
looks good, just a few minor comments

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/plugins/point-cloud/index.js
> +  fastify.decorate(module.exports.graphs, graphs);
I don't think we are using `graphs` in this example, can be removed

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/plugins/point-cloud/index.js
> +module.exports.graphs  = Symbol('graphs');
same as previous, `graphs` not used

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/plugins/point-cloud/index.js
> +    }
```suggestion
```

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/plugins/point-cloud/index.js
> +function layoutAndRenderGraphs(clients) {
Could be renamed to PointCloud instead? 
```suggestion
function layoutAndRenderPointCloud(clients) {
```

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/render/render.js
> +  async render(props = {}, graph = {}, state = {}, events = [], frame = 0) {
```suggestion
  async render(props = {}, state = {}, events = [], frame = 0) {
```

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/render/render.js
> +  const makeLayers = (deck, graph = null) => {
I think renaming `graph` to `pointCloud` might lead to less confusion?
```suggestion
  const makeLayers = (deck, pointCloud = null) => {
```

2021-10-29 21:15 UTC, AjayThorve commented on modules/demo/ssr/point-cloud/render/worker.js
> +}
```suggestion
function render({props = {}, state = {}, event = [], frame = 0}) {
  return renderer.render(props, state, event, frame);
}
```

2021-10-29 22:42 UTC, mzegar commented on modules/demo/ssr/point-cloud/plugins/point-cloud/index.js
> +function graphSSRClients(fastify) {
Should this be renamed as well?

2021-10-29 22:43 UTC, mzegar commented
I can throw up an issue to combine some of this duplicate code since I think I'm transitioning over to the thrust stuff next week.

2022-01-18 23:16 UTC, trxcllnt commented
Closing in favor of https://github.com/rapidsai/node/pull/348

2022-01-18 23:16 UTC, closed without merging